version: "3.8"

services:
  app:
    image: mlfinancial
    working_dir: /app
    volumes:
      - ./:/app
    environment:
        batch_size: 128
        time_steps: 20
        mode: prediction
        model_type: conv2d
        model_load_name: conv2d_model.h5
        use_docker: true
        ticker: btcusd
        interval: 1h