version: "3.8"

services:
  app:
    image: mlfinancial
    working_dir: /app
    volumes:
      - ./:/app
    environment:
        batch_size: 128
        time_steps: 5
        mode: training
        model_type: lstm
        model_load_name: 1.0103_3.1973_50.5134.h5
        ensemble: average
        ticker: btcusd
        interval: 1h
        cryptowatch_key: 'your key here'