version: "3.8"

services:
  app:
    image: mlfinancial
    working_dir: /app
    volumes:
      - ./:/app
    environment:
        batch_size: 128
        time_steps: 48
        mode: training
        model_type: conv2d
        model_load_name: 0.9405_8.7345_52.7232.h5
        use_docker: true
        ticker: btcusd
        interval: 1h
        cryptowatch_key: 'your key here'